### ISSUE TITLE
Roster query should check cron log and report warnings

### ISSUE THREAD

**Issue by lhkbob** [eve-val/eve-roster#112]
Now that other requests are able to return stale data with an additional warning message, it makes sense that the roster could check if it is out of date.

These warnings would be triggered by failures in the last executed cron job for the roster (either the member list, siggy, or killboard), instead of missing access token or failure in the ESI end point at the time of the request. Although, one of the potential causes for a failed cron execution is an ESI/XML failure at that point in time.

This isn't high priority since the admins can view the log anyways, but this would make that information more accessible.

**Comment by lizthegrey** [comment]
good enough visibility with honeycomb now into failing jobs
