### ISSUE TITLE
Corp API key and credential setup and management

### ISSUE THREAD

**Issue by wffurr** [eve-val/eve-roster#183]
Right now we have this hacky combination of database fields and environment variables.  The DB fields are intialized by a CLI [quicksetup script](https://github.com/7sempra/eve-roster/blob/master/bin/quicksetup.js) that reads from a `setup.json` file not in repo, and the environment variables are managed with a `manage.py` script similarly not in the repo with credentials hardcoded in it.

We should either standardize on one of the formats and have tooling for that in the repo, with credentials stored elsewhere, or actually build a UI for setup and management.

In our most recent example, we had a corp CEO change which necessitated rolling the corp API key.  The key roll had to be done by hand in the database, which is less than ideal from an ongoing admin perspective.

**Comment by lizthegrey** [comment]
done now with the json config I think
