### ISSUE TITLE
Parallelize syncCorps

### ISSUE THREAD

**Issue by lhkbob** [eve-val/eve-roster#288]
Right now the corporation id lookup for each character is executed serially.  With a little restructuring, we can make many info requests and collect all of the characters' corp ids at once before saving each to the DB.  Alternatively, we can look at the newer affiliations end point that takes a list of character ids.

This should hopefully reduce the tasks' execution time from .5 to 3 minutes to several seconds.

**Comment by lizthegrey** [comment]
fixed by #520 and #530
