### ISSUE TITLE
development setup suggests node-foreman... is that still accurate?

### ISSUE THREAD

**Issue by jessitron** [eve-val/eve-roster#663]
I tried to follow dev setup instructions, but "nf" complains about not finding a Procfile.
node-foreman but no Procfile?
Are the docs out of date?

**Comment by ayust** [comment]
@lizthegrey I seem to recall you maybe switched our build system? Is there a doc that didn't get updated?

**Comment by lizthegrey** [comment]
ah, I don't run node-foreman for local dev, I just straight up run `node out/server/server.js`.

I never managed to get node-foreman to work for me, even before I made any changes.
